name: Deploy new data

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update_data]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install Go 1.17
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'    
      run: go version
    - name: Install dependencies & build
      run: |
        go get
        go build -o main
    - name: Run program
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        KYOTO_ADDR: ${{ secrets.KYOTO_ADDR }}
        MY_ADDR:  ${{ secrets.MY_ADDR }}
      run: |
        TZ= ./main ${CLIENT_ID} ${CLIENT_SECRET} ${REFRESH_TOKEN} ${KYOTO_ADDR} ${MY_ADDR}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./data
        publish_branch: gh-pages
        allow_empty_commit: true
